### ISSUE TITLE
Intervals in case of recall of very overdued cards are too large

### ISSUE THREAD

**Issue by hugomarins** [open-spaced-repetition/fsrs4remnote#11]
As far as I can see, the FSRS is not following the formula for the new Stability after a successful recall. In case of a very overdued card, the stability got almost twice my calculated new stability:

![image](https://user-images.githubusercontent.com/54500828/217061455-3124754b-aedb-4cb9-8bb7-a7ae3f55ff39.png)

My settings are: 1, 2.5, 5, -1, -1, 0.2, 1.5, -0.12, 0.8, 3, -0.2, 0.45, 1.2

The system returns a new stability of 1.6y for this card.

![image](https://user-images.githubusercontent.com/54500828/217063051-bdfcffab-33f8-4b00-b090-77af409d1374.png)

But, handling the formula, it appeared to me that the interval should instead be about 4.5x the last stability (~60 days), that is, something like 0.74 years. (in the link below, my calculation) 

https://www.geogebra.org/m/f3zrfrby

Is there any mistake in the formula I used? Can you just check if the previous Stability is been considered correctly, that is, without reckoning the overdue period, already considered in the Retrievability?

Thanks!

**Comment by L-M-Sherlock** [comment]
The formula is correct when all reviews are scheduled by FSRS. If you reviewed the card with other algorithm in first few times, the formula will be inaccurate.

**Comment by hugomarins** [comment]
This post is a little old. If I note something strange again, I'll let you know. These cases happen in very overdued cards. I really think the way FSRS deals with very overdued cards is too optimistic and not that trustworthy (the same applies for Anki/SM-2 algorithms). And w8 in the formula is also not fit for reducing the aggressiveness of the increase in intervals of very overdued cards [as it just multiplies (1 - R) in the exponent] (I tried all possible combinations of weights in geogebra, and always cards very overdued would have a very large increase in stability, w8 not modulating this aggressiveness). I would really want to be able to chose if I want this behavior or not. I know that it is not the behavior of current schedulers commonly used, but I only would want you to know that the possibility of modulating it is a thing that I aspire a lot! Anyway, thanks for your incredible work!

**Comment by L-M-Sherlock** [comment]
> And w8 in the formula is also not fit for reducing the aggressiveness of the increase in intervals of very overdued cards [as it just multiplies (1 - R) in the exponent] (I tried all possible combinations of weights in geogebra, and always cards very overdued would have a very large increase in stability, w8 not modulating this aggressiveness).

Do you have any suggestive function for the overdue cards? I plan to update the formula of FSRS.

**Comment by hugomarins** [comment]
I spent this morning trying to find a way of achieving what I intend, and I think I was able to figure out a possible solution.

### The problem:
I'll use a concept of "overdueness" meaning the factor t days / Stability you use in the retrievability formula:
$$R(t,S) = 0.9^{\frac{t}{S}}$$
So, if overdueness is 1, it means the card is being reviewed in the scheduled day. If overdueness is 6, it means I am reviewing the card after a time 6x larger than that one proposed by the algorithm.

**Anki/SM-2 scheduler and FSRS at present give too long intervals when we review cards very overdued (very out of schedule).**

Looking at FSRS formula, and isolating the w8 term (the retrievability term), I made a graph (with overdueness in the ordinates) showing the Stability Increase (only due to the retrievability term), and the "bonus" someone would get when recalling a card that is overdued, that is, how many times the new stability will be larger that that if I have reviewed the card in the correct time.

You can see this graph in Geogebra: https://www.geogebra.org/calculator/kbqchnep

The graph shows that, no matter which w8 setting, I can't flatten the curve of overdue bonus increase:

w8 = 0.8 (default value)
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/0af44cbc-caf0-4d3e-a699-ce2e16e30ffe)

w8 = 0.1 
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/23608fc0-6988-464f-bda1-3f6d7ae04c88)

### The proposed solution
After dealing with the graph in search of a formula that would flatten the overdue bonus at some point, I realized that **w8** is a **recall retrievability factor**, and as such it could be transferred to the Retrievability formula:
$$R(t,S) = 0.9^{w_8 \cdot \frac{t}{S}}$$
This way, w8 would be a weight that, if increased enough (coupled with a decrease in w6, of course), would allow the desired stopping the bonus increase for overdueness at a reasonable point (such as overdueness about 3x the original interval):
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/efe1998e-c188-4348-bb1a-4a2a296f4f0d)

The new stability after recall would than have to be altered (as w8 would have been removed to R):
$$S^\prime_r(D,S,R) = S\cdot(e^{w_6}\cdot (11-D)\cdot S^{w_7}\cdot(e^{(1-R)}-1)+1).$$

### The simulation
I did a simulation which would put the current behavior and the behavior after the proposed changes, side by side.

This is also in GeoGebra: https://www.geogebra.org/calculator/yygnjuq3

In this simulation, I used in the abscissa axis an Anki Factor comparison, that you call $SInc = \cfrac{S^\prime_r(D,S,R)}{S}$

There, my previous configuration (w8 = 0.8 and w6 = 2.6) would be almost exactly matched by new settings of (w8 = 8.8 and w6 = 0.3) in the proposed new formula, if overdueness is 1:
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/30977305-edfa-46bb-ad2e-cae9d8e7e3d5)

But the behavior would be very different in case of very overdued cards (below, overdueness is 6):
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/7d87f62d-4744-41fb-ae7f-873ee686bf0d)

If, for example, I review a card with last interval (Stability) of 30 days six months after the previous review (that is, with and overdueness of 6), in the current formula I would get a new stability 10x larger than the current one (about 10 months). But using the new setting and new formula above, I would get a new stability about 4.5x larger than the previous (4,5 months). Thus, we would be really able to modulate the desired retrievability effect on stability, what I think is not the case in the current formula.
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/5169cdb1-e4ef-4cf7-90b6-73fc82b8a329)

Maybe @bjsi and @sobjornstad could also give their opinion.

**Comment by L-M-Sherlock** [comment]
> Retrievability formula:
> $$R(t,S) = 0.9^{w_8 \cdot \frac{t}{S}}$$

We shouldn't modify the formula of forgetting curve for this issue. S has its physical meaning - the elapsed days when the retrievability decays from 100% to 90%. In your proposed formula, w_8 will change the physical meaning.

**Comment by L-M-Sherlock** [comment]
> The new stability after recall would than have to be altered (as w8 would have been removed to R):
> $$S^\prime_r(D,S,R) = S\cdot(e^{w_6}\cdot (11-D)\cdot S^{w_7}\cdot(e^{(1-R)}-1)+1).$$

We can move the w_8 out of R:

$$S^\prime_r(D,S,R) = S\cdot(e^{w_6}\cdot (11-D)\cdot S^{w_7}\cdot(e^{(1-R^w_8)}-1)+1).$$

**Comment by hugomarins** [comment]
Yeap, it would also work perfectly!! I would be very happy if you implement this change!
