### ISSUE TITLE
[FEATURE] Offline support

### ISSUE THREAD

**Issue by yuuz233** [open-spaced-repetition/fsrs4remnote#13]
**Is your feature request related to a problem? Please describe.**
When offline the custom scheduler is fallbacked into default scheduler.

**Describe the solution you'd like**
I asked Remnote's support and they say it was not a problem on their end, FSRS does not need network (as anki's implementation) so is that similar story in Remnote's implementation?

**Comment by L-M-Sherlock** [comment]
@bjsi, could you check it? I don't know why the plugin requires network.

**Comment by coldenate** [comment]
This is a good feature request for RemNote's Team as individual plugins cannot exactly control this.

**Comment by bjsi** [comment]
Hey, yeah we will support this eventually, it's on the task list, but not a priority atm.
