### ISSUE TITLE
Is the function "next_difficulty" correct? It is different from "fsrs4anki".

### ISSUE THREAD

**Issue by jiangqizheng** [open-spaced-repetition/fsrs4remnote#15]
**fsrs4anki**
![](https://secure2.wostatic.cn/static/dCGFLnN7vGFGLkDceRWJyM/image.png?auth_key=1683101008-vJyTHRRgwZkf4PnugErwbV-0-aa0a51e2bbc3f64541a2b91913366328)

**fsrs4remnote**
<img width="492" alt="image" src="https://user-images.githubusercontent.com/21155771/235866912-27781672-2f19-49f0-98e1-6e1ccb4b73ba.png">
The rating here starts from 0.

**Comment by jiangqizheng** [comment]
If choose "again"

**fsrs4anki**
next_d = d + w[4] * (1 - 3)

**fsrs4remnote**
next_d = d + w[4] * (0 - 3)

next_d is different？

**Comment by L-M-Sherlock** [comment]
> next_d = d + w[4] * (1 - 3)

Here rating is 1, but ratings[rating] is 0. So they are the same.

**Comment by jiangqizheng** [comment]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/21155771/235900041-8b51d32b-edbb-4e49-91c3-e89edf09491e.png">

There is no 0 in "ratings"

did i miss something?

**Comment by L-M-Sherlock** [comment]
I notes the inconsistency between FSRS4Anki and FSRS4RemNote. `next_difficulty` need to remedy. Thanks for your report.

**Comment by jiangqizheng** [comment]
You’re welcome. I happened to be trying it
