### ISSUE TITLE
Initial Stability when the first rating is again

### ISSUE THREAD

**Issue by hugomarins** [open-spaced-repetition/fsrs4remnote#17]
No matter which value is set for w0, when the first rate is again, the card is shown again in a few minutes, and after that, the new interval is 48h (and not that set in w0).

**Comment by hugomarins** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/851b6391-2f40-47be-a7a9-d1ac8f27187f)

![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/062cd02d-a687-4792-9e08-9fa51d7060fd)

![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/6aa51294-b0fe-4be6-9ed5-66efa2b6bdb6)

**Comment by L-M-Sherlock** [comment]
It is because the `goodIvl` is always greater than `hardIvl` + 1:

https://github.com/open-spaced-repetition/fsrs4remnote/blob/90edc9e188378516c64b01b5d0cb3364048395ba/src/widgets/index.tsx#L111-L121

**Comment by L-M-Sherlock** [comment]
I fixed it. Now when you press `hard` in learning state, the hard interval will be 10 mins and the good interval will depend on your parameters. It could be 1 day.
