### ISSUE TITLE
After pressing Hard in a card in Review stage, it appears that the intervals proposed in the next repetition are wrong

### ISSUE THREAD

**Issue by hugomarins** [open-spaced-repetition/fsrs4remnote#20]
Sorry if what I am going to tell sounds nonsense, but as I do not know programming language, I try to figure out things, and maybe my thoughts will not be correct.

I've been using FSRS for a while, and I noted a strange behavior after answering Hard to a card. 

It appears that, although the next interval is set correctly, there is another stored information for "stability", and that this stored "stability" does not match the next interval set.

![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/12ef3424-2043-41ee-bbfc-d34ade4dbf30)

Like I said, I don't know how to interpret the code properly, but the behavior that the plugin appears to have is this:

1) When pressing Hard to a card in the Review stage, the next interval is set correctly.
2) The "stability" information stored, otherwise, and used in the next repetition of the card, appears to be the "stability" the card would have if I had pressed "God" in that previous review, and not the true interval of the card.
3) This so being, the intervals calculated for item 2 above (that is, next repetition of the card rated Hard in item 1) are too large, as if the stored "stability" was that of having pressed Good, and not Hard, in item 1 above. 

Could you please check the code and see if maybe there is something wrong? Thanks!

**Comment by L-M-Sherlock** [comment]
> 3\. This so being, the intervals calculated for item 2 above (that is, next repetition of the card rated Hard in item 1) are too large, as if the stored "stability" was that of having pressed Good, and not Hard, in item 1 above.

Is it too large? How do you draw to this conclusion?



> It appears that, although the next interval is set correctly, there is another stored information for "stability", and that this stored "stability" does not match the next interval set.

It is intended. The hard interval is calculated from the last stability instead of the current stability.

**Comment by hugomarins** [comment]
I draw the conclusion that the interval is too large based on the formula:
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/95e6226e-9c7d-4446-b514-1c5a8c2db7a9)

Making the calculations, I saw that the results were like if they considered a anterior stability larger than the real one.

I'm trying to find an example in my reviews to make it clearer. As soon as I get an example, I'll show here.

**Comment by L-M-Sherlock** [comment]
> This is absolutely correct, and the intervals given when pressing Hard are correct. My concern is that, in the next review, the system will use as last stability a figure that is different from the real last interval.

Yep, the last interval is not always based on the last stability, which will also affect the retention. But the design for the hard interval is used to calculate the interval based on the last interval.

**Comment by L-M-Sherlock** [comment]
In Anki, the hard interval is always last interval * 1.2 (or custom hard factor).

**Comment by hugomarins** [comment]
Yeap, bus the situation I think happened is more os less this:

1 - I reviewed a card with a 15 days last interval. By my standard settings, pressing Good would return a 48 days new interval:
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/c086af99-9268-480d-889d-4713c0611f98)

But I answered hard with the intention of not increasing the stability that much, as the content was not well ingrained in my head yet; so my next interval got 18 days (last interval * 1.2).

2 - 18 days after this, I will review the card again. Which last stability will be considered for the calculation of the next stability? I think it should be 18 days (my feedback beforehand told the system not to increase the stability that much). But it appears (I'll try to prove it as soon as I find a card fitting the situation) that at this second moment, the new stability is being calculated based on a "last stability" of 48 days (instead of 18 days).
If I will press Good in this second situation, my new interval would be:
A) 55 days, as I think should be the case (considering a last stability of 18 days)
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/5ab7e4fd-65c6-434a-abcf-7ecd677cc13b)
B) or 114 days, as appears to me the system is doing (considering a last stability of 48 days)?
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/2eca231b-3577-4f41-af6d-992a14c99a2a)

The difference in the output is large (B next interval is twice that of A).

**Comment by hugomarins** [comment]
Found one example!

![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/0762c4cd-3e3c-4b26-aa8e-d841ff40c10c)

7 days ago I reviewed this cards. The card had a last interval of 6 days. Is I had pressed Good, I would get an interval of about 25 days.
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/c2524b4d-d4a1-44f4-a889-c31fd3049dd6)

Ass I found it difficult to answer, I rated Hard, and got a next interval of 7 days.

Today, I reviewed the card again. If I would press Good: 

A) I should get an interval of about 28 days or 0.94 months (considering that the plugin cannot yet change the difficulty of the card through history, and so uses the default difficulty of 5 even if I pressed hard once before):
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/426f2b45-9d5d-49d3-9529-ad1d3e8b2f86)

B) If the last interval used was the 25 days (that I thought may be the case, even if it should not), the next interval should be about 70 days or 2.33 months:
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/e25a55a4-9ee8-48c6-8f88-0d32e6ba117b)

But what the system produced was a different result:
![image](https://github.com/open-spaced-repetition/fsrs4remnote/assets/54500828/ba209d2a-6c07-4b35-85f6-73c21bbb71f9)

The new interval for Good is 1.2 months (28% higher than the calculated in A, but not that higher as calculated in B). It is strange, but acceptable. 

But the case for pressing Hard again is worst. If my last interval was 7 days, pressing hard once more should give an interval of 8 or 9 days (last interval * 1.2), but the output from the system is much higher (1 month). At least in this case appears that it is using that 25 days stability of B, and so giving a next interval of 25 * 1.2 = 30 days.

This is problematic and strange. If you could give a look in this, I would be very grateful. Thanks in advance!

**Comment by L-M-Sherlock** [comment]
> This is problematic and strange. If you could give a look in this, I would be very grateful. Thanks in advance!

FSRS4Anki also deals with the hard like this. The hard interval is based on the last stability. It will ensure the hard interval is always shorter than good interval and longer than the last interval. In you case, I recommend pressing `again`.

**Comment by hugomarins** [comment]
Ok, but my point here is not against hard interval being based on the last stability (I never questioned it). My question is what "last stability" is being used for calculating the hard interval. In the example I brought above, I think that pressing Hard the second time (in the review I did today) should consider the last interval (i.e., 7 days) as the last stability. If it was the case, the hard interval output (for todays review) should be something around 8 or 9 days, and not the 1 month interval that the system brought. It appears that hard interval in that case is being calculated over an imaginary last stability, rather than on the real last stability.

**Comment by L-M-Sherlock** [comment]
> In the example I brought above, I think that pressing Hard the second time (in the review I did today) should consider the last interval (i.e., 7 days) as the last stability. If it was the case, the hard interval output (for today's review) should be something around 8 or 9 days, and not the 1 month interval that the system brought.

After you press the hard first time, the stability has been updated to 25 days. The interval is 7 days. The last interval is not equal to the current stability.

**Comment by hugomarins** [comment]
Thanks for letting me know. I thought it was a bug. It's quite different from Anki/SM-2 behavior. I always thought that stability and interval was coincident concepts. Now I understood your point, even though I don't like it (yet). 

By the way, thanks for sharing FSRS. I am very convinced of its suitability to include the idea of memory stabilization; it also allows having larger factors when the card is young and smaller factors when it is very mature, what I always sought before. I hope that its compatibility with RemNote may be increased in the short term. And when possible I'll bring my suggestions and my notes.

**Comment by L-M-Sherlock** [comment]
> By the way, thanks for sharing FSRS. I am very convinced of its suitability to include the idea of memory stabilization; it also allows having larger factors when the card is young and smaller factors when it is very mature, what I always sought before. I hope that its compatibility with RemNote may be increased in the short term. And when possible I'll bring my suggestions and my notes.

What do you mean by the compatibility?
