### ISSUE TITLE
[FEATURE]FSRS4RemNote Optimizer中的2.1 Define the model仍使用“ fsrs4anki_optimizer==3.25.3”版本，是否需要更新 ？

### ISSUE THREAD

**Issue by veritaswiki** [open-spaced-repetition/fsrs4remnote#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by veritaswiki** [comment]
目前使用三已出现依赖兼容性报错
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
plotnine 0.12.4 requires numpy>=1.23.0, but you have numpy 1.22.4 which is incompatible.
tensorflow 2.14.0 requires numpy>=1.23.5, but you have numpy 1.22.4 which is incompatible.

**Comment by L-M-Sherlock** [comment]
现在 fsrs4anki_optimizer 的主版本号已经到 4 了，和 3 不兼容。

**Comment by L-M-Sherlock** [comment]
现在应该可以了
